name: CI/CD unitap

on:
  push:
    branches: [ master ]

  workflow_dispatch:

jobs:
  build:
    runs-on: self-hosted

    defaults:
      run:
        working-directory: /root/gitlab.com/unitap
        
    steps:
      - name: Master deploy
        run: |
          git pull origin master
          yarn install
          yarn generate
          yarn build
          pm2 reload 38