name: CI/CD unitap

on:
  push:
    branches: [ master ]

  workflow_dispatch:

jobs:
  clone:
    runs-on: self-hosted

    defaults:
      run:
        working-directory: /root/gitlab.com/unitap
        
    steps:
      - name: Clone
        run: git pull origin master
        
      - name: Install library
        run: yarn install
        
      - name: Generate statics page
        run: yarn generate
        
      - name: Build
        run: yarn build
        
      - name: Reload PM2
        run: pm2 reload 38
        
